
apiVersion: v1
kind: Service
metadata:
  name: app-service

spec:
  type: NodePort

  selector: 
    app: app
  
  ports:
    - name: http
      port: 80
      nodePort: 30090
      targetPort: http

